export {
  PORT,
  NODE_ENV,
  API_PREFIX,
  UPLOAD_DIR,
  DEFAULT_ORGANIZATION_ID,
  CURRENT_PROGRAM_DOMAIN,
  BACKEND_URL,
  CORS_ORIGIN,
  JWT_SECRET,
  JWT_EXPIRES_IN,
  MAX_FILE_SIZE_BYTES,
  ALLOWED_MIME_TYPES,
  MAX_ATTEMPTS,
  JOB_TIMEOUT_MS,
  RETRY_BACKOFF_BASE_MS,
  SCANNED_PDF_WORDS_PER_PAGE_THRESHOLD,
  OCR_CONFIDENCE_REVIEW_THRESHOLD,
  PLATFORM_DISPLAY_NAME,
  PLATFORM_SYSTEM_NAME,
  getCorsOrigins,
} from "./core/config/env.js";

export const PROGRAM_DISPLAY_NAME = "Community Chronicle";
export const PROGRAM_SYSTEM_NAME = "community-chronicle";
